# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f9DS2opiZKyDuOEpIQwl4B-nZhM4uiYW
"""

import streamlit as st
import pandas as pd
import joblib

# -----------------------------
# 🎓 Load the Trained Model
# -----------------------------
# Make sure your trained logistic regression model is saved as 'admission_model.pkl'
model = joblib.load("Jawad-Admission-main/admission_model.pkl")

st.title("🎓 University Admission Prediction App")
st.write("Enter your academic details to check your **chance of admission**!")

# -----------------------------
# 🧮 Input Fields
# -----------------------------
gre = st.number_input("GRE Score (out of 340)", min_value=260, max_value=340, value=320)
toefl = st.number_input("TOEFL Score (out of 120)", min_value=0, max_value=120, value=100)
cgpa = st.number_input("CGPA (out of 10)", min_value=0.0, max_value=10.0, value=8.0)
sop = st.number_input("Statement of Purpose (1.0 - 5.0)", min_value=1.0, max_value=5.0, value=3.0)

# -----------------------------
# 📊 Normalize if your model was trained on a 1–10 scale
# -----------------------------
# Adjust this based on your model scaling
scaled_data = pd.DataFrame({
    'GRE': [gre],      
    'TOEFL': [toefl],  
    'CGPA': [cgpa],
    'SOP': [sop] 
})

# -----------------------------
# 🔍 Make Prediction
# -----------------------------
if st.button("Predict Admission Chance 🎯"):
    prediction = model.predict(scaled_data)
    probability = model.predict_proba(scaled_data)

    st.subheader("📈 Prediction Result:")
    if prediction[0] == 1:
        st.success(f"✅ You are **likely to get admitted!** 🎉")
    else:
        st.error(f"❌ Admission is **less likely.** Try improving your profile!")

    st.write("**Probability of Admission:**", round(probability[0][1] * 100, 2), "%")
